//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DimMakerLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DimMakerLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encoding 1257
        ///in_file &quot;FRONT_GEO&quot;
        ///out_file &quot;cP_FRONT_GEO&quot;
        ///view_scale 25.000000
        ///cut_on 0
        ///cut_length 2.000000
        ///cut_min_dist 400.000000
        ///cut_skew_parts 0
        ///size_mode 0
        ///xmin -0.660000
        ///xmax 6330.660000
        ///ymin -755.660000
        ///ymax 755.660000
        ///depth_neg 100.660000
        ///depth_pos 100.660000
        ///label_height 3.500000
        ///label_position 0
        ///label_colour 153
        ///np_extrema_size 0.000000
        ///Unfolded 0
        ///Reflected 0
        ///StyleName &quot;cP_FRONT_GEO&quot;
        ///HoleSymbol 0
        ///Unwarped 0
        ///LocationBy &quot;ProjectBasePoint&quot;
        ///Elevation_datum_point 0.000000
        ///Elev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEO_FRONT {
            get {
                return ResourceManager.GetString("GEO_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encoding 1257
        ///in_file &quot;FRONT_REINF_V1&quot;
        ///out_file &quot;standard&quot;
        ///view_scale 25.000000
        ///cut_on 0
        ///cut_length 2.000000
        ///cut_min_dist 400.000000
        ///cut_skew_parts 0
        ///size_mode 0
        ///xmin -0.660000
        ///xmax 6330.660000
        ///ymin -755.660000
        ///ymax 755.660000
        ///depth_neg 100.660000
        ///depth_pos 100.660000
        ///label_height 3.500000
        ///label_position 0
        ///label_colour 153
        ///np_extrema_size 0.000000
        ///Unfolded 0
        ///Reflected 0
        ///StyleName &quot;cP_FRONT_REINF&quot;
        ///HoleSymbol 0
        ///Unwarped 0
        ///LocationBy &quot;ProjectBasePoint&quot;
        ///Elevation_datum_point 0.000000
        ///E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REINF_FRONT {
            get {
                return ResourceManager.GetString("REINF_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encoding 1257
        ///in_file &quot;0000REINFVERTATTR&quot;
        ///view_scale 10.000000
        ///cut_on 0
        ///cut_length 2.000000
        ///cut_min_dist 400.000000
        ///cut_skew_parts 0
        ///size_mode 0
        ///xmin -100.010000
        ///xmax 100.010000
        ///ymin -802.400000
        ///ymax 755.000000
        ///depth_neg 33.470000
        ///depth_pos 200.000000
        ///label_height 3.500000
        ///label_position 0
        ///label_colour 153
        ///np_extrema_size 0.000000
        ///Unfolded 0
        ///Reflected 0
        ///StyleName &quot;0000REINFVERTATTR&quot;
        ///HoleSymbol 0
        ///Unwarped 0
        ///LocationBy &quot;ProjectBasePoint&quot;
        ///Elevation_datum_point 0.000000
        ///ElevationDatumSw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REINF_VERT_SPEC {
            get {
                return ResourceManager.GetString("REINF_VERT_SPEC", resourceCulture);
            }
        }
    }
}
